### ISSUE TITLE
Add a section to show date and current time while adding a book.

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/lib#3]
You are required to add a section to show time and data of adding a particular book to the list.

![image](https://user-images.githubusercontent.com/78257493/136212188-c9378cab-863a-4907-a41e-497a77198e65.png)

Yo can add a column near type column !

**Comment by JanviRaina** [comment]
I can try this. You can assign this to me.

**Comment by Deepak91168** [comment]
Go Ahead!!
@JanviRaina 
Assigned to you!
Please also include the SS of final result in PR
feel free to be creative
